name: json_schema2
version: 2.0.0+1
description: Provide support for validating instances against json schema
homepage: https://github.com/workiva/json_schema

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  collection: ^1.15.0
  logging: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0
  rest_client: ^2.0.0
  uri: ^1.0.0

dev_dependencies:
  test: any
